# Generated by Django 5.2.15 on 2026-06-28 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='guild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='guilds.guild', verbose_name='Gildia'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='guild_role',
            field=models.CharField(default='Nowicjusz', max_length=50, verbose_name='Rola w Gildii'),
        ),
    ]
