# Generated by Django 5.2.15 on 2026-07-22 08:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_sharedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar_users', to='users.sharedimage'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='O mnie'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Konto zweryfikowane'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_active',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ostatnio aktywny'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_daily_reward',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ostatnia dzienna nagroda'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='skill_points',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Punkty umiejętności'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.JSONField(blank=True, default=dict, verbose_name='Umiejętności'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dobroty',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dobroty'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='experience',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Doświadczenie'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Poziom'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reputation',
            field=models.IntegerField(default=0, verbose_name='Reputacja'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('FRIEND', 'Znajomy'), ('BLOCKED', 'Zablokowany')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
