# Generated by Django 5.2.15 on 2026-06-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        ('users', '0003_sharedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='forum_images/', verbose_name='Dołączone zdjęcie'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='forum_posts', to='users.sharedimage', verbose_name='Dołączone zdjęcia'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="Lista tagów, np. ['technologia', 'nauka']"),
        ),
    ]
