# Generated by Django 5.2.15 on 2026-06-28 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forumpost_image_forumpost_images_forumpost_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='image',
        ),
    ]
