# Generated by Django 5.2.15 on 2026-06-28 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł zadania')),
                ('description', models.TextField(verbose_name='Opis')),
                ('task_type', models.CharField(choices=[('FIELD', 'Terenowe'), ('SCHEDULE', 'Harmonogramowe')], max_length=20, verbose_name='Typ zadania')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Dostępne'), ('IN_PROGRESS', 'W trakcie'), ('VERIFYING', 'Weryfikacja'), ('COMPLETED', 'Zakończone')], default='AVAILABLE', max_length=20)),
                ('bounty', models.IntegerField(default=0, verbose_name='Nagroda (Dobroty)')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
